### ISSUE TITLE
Missing  make_buildnr.sh.in

### ISSUE THREAD

**Issue by buffstop** [andreasfink/ulibdb#1]
Building with current Xcode 12.5, configuring fails for me due to `config.status: error: cannot find input file: `make_buildnr.sh.in'`.

`...
Configuring for ulibdb version 1.15.0 ...

Running system checks ...
checking build system type... x86_64-apple-darwin20.4.0
checking host system type... x86_64-apple-darwin20.4.0
./configure: line 2444: CoreFoundation: command not found
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking for ulib_cpu_count in -lulib... no

Config options ...
Using Release target

Checking for PostgreSQL support ...
checking for "/usr/local/postgresclient/include/libpq-fe.h"... no
checking for "/usr/include/postgresql/libpq-fe.h"... no
./configure: line 3935: mysql_config: command not found
./configure: line 3936: mysql_config: command not found
./configure: line 3942: mysql_config: command not found

Generating output files ...
configure: creating ./config.status
config.status: creating Makefile.osx
config.status: creating Makefile.linux
config.status: creating Makefile.freebsd
config.status: creating ulibdb.pc
config.status: error: cannot find input file: `make_buildnr.sh.in'
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure`

**Comment by andreasfink** [comment]
missing file has been added and repo updated.

**Comment by buffstop** [comment]
Thanks for the quick help. Appreciated!

It still fails differently with `cannot find input file: `make_buildnr.sh.in'` now.

Now in line 1 of config.status:

`#! /bin/shmake_buildnr.sh.in`

**Comment by andreasfink** [comment]
PS: you need to run ./configure once to let it generate make_buildnr.sh from it.
