### ISSUE TITLE
ulibdb_config.h is not found

### ISSUE THREAD

**Issue by buffstop** [andreasfink/ulibdb#2]
Building with Xcode 12.5, `ulibdb_config.h` is not found (and does really not exist).

Is that meant to be manually created from ulibdb_config.h.in?

I have tried that defining only:
`/* define if you have postgres Support */
//#undef HAVE_PGSQL
#define HAVE_PGSQL`

It fails building in many places, trying to use MySQL. Example in ulibdb.m:39:

`if (mysql_library_init(0, NULL, NULL)) // Error: Implicit declaration of function 'mysql_library_init' is invalid in C99`

It looks to me that its trying to use mysql even is undefined in ulibdb.config.h:
`#undef HAVE_MYSQL`

**Comment by andreasfink** [comment]
ulibdb_config.h is created from ulibdb_config.h.in
when you run ./configure
you have to run this once on all my ulib* projects.

**Comment by buffstop** [comment]
That worked, thx. I thought  ./configure is triggered by Xcode "Build Phase" "Run Script" phase.
